vich_uploader:
    db_driver: orm
    metadata:
      type: attribute

    mappings:
        etudiant_images:
            uri_prefix: /images/etudiants
            upload_destination: '%kernel.project_dir%/public/images/etudiants'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
